version: '3'

services:
  db:
    image: mysql:5.7
    container_name: db6034
    environment:
      MYSQL_ROOT_PASSWORD: my_secret_password
      MYSQL_DATABASE: app_db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_user_pass
    ports:
      - "6034:3306"
    volumes:
      - ./var/data/db:/var/lib/mysql
